# InfinityJetpack configuration file
# Version v1.7.0 Beta 1
# Based on EasyJetpack by j_selby

# These Jetpacks were created by j_selby.
jetpacks:
    # Traditional, or 'puff' Jetpack
    traditional:
        # Is this Jetpack enabled?
        enabled: true
        # The name of the Material used.
        material: GOLD_CHESTPLATE
        # Is durability enabled on this Jetpack?
        durability: true
        # Is the Jetpack craftable?
        craftable: true
        # Is the Jetpack repairable?
        antianvil: true
    burst:
        # Is this Jetpack enabled?
        enabled: true
        # The name of the Material used.
        material: GOLD_CHESTPLATE
        # Is durability enabled on this Jetpack?
        durability: true
        # Is the Jetpack craftable?
        craftable: true
        # Is the Jetpack repairable?
        antianvil: true
    teleport:
        # Is this Jetpack enabled?
        enabled: true
        # The name of the Material used.
        material: CHAINMAIL_CHESTPLATE
        # Is durability enabled on this Jetpack?
        durability: true
        # Is the Jetpack craftable?
        craftable: true
        # Is the Jetpack repairable?
        antianvil: true
    rocket:
        # Is this Jetpack enabled?
        enabled: true
        # The name of the Material used.
        material: CHAINMAIL_CHESTPLATE
        # Is the Jetpack craftable?
        craftable: true
        # Is the Jetpack repairable?
        antianvil: true
    boots:
        # Are these fallboots enabled?
        enabled: true
        # The name of the Material used.
        material: LEATHER_BOOTS
        # Is durability enabled on these boots?
        durability: true
        # Are the boots craftable?
        craftable: true
        # Do the boots need a Jetpack to function?
        jetpackrequired: false
        # Is the Jetpack repairable?
        antianvil: true
# Infinity Laboratories Jetpacks
# These jetpacks have been created by Infinity Laboratories, and
# are distributed by other companies.
    entry:
        # Is this jetpack enabled?
        enabled: true
        # The name of the material used.
        material: LEATHER_CHESTPLATE
        # Is the jetpack craftable?
        craftable: true
        # Is the jetpack repairable?
        antianvil: true
    infinity:
        # Is this jetpack enabled?
        enabled: true
        # The name of the material used.
        material: DIAMOND_CHESTPLATE
        # Is the jetpack craftable?
        craftable: true
        # Is the jetpack repairable?
        antianvil: true
    infinityrocket:
        # Is this jetpack enabled?
        enabled: true
        # The name of the material used.
        material: DIAMOND_CHESTPLATE
        # Is the jetpack craftable?
        craftable: true
        # Is this jetpack repairable?
        antianvil: true
    slimepack:
        # Is this jetpack enabled?
        enabled: true
        # The name of the material used.
        material: LEATHER_CHESTPLATE
        # Is the jetpack craftable?
        craftable: true
    rocketboots:
        # Is this jetpack enabled?
        enabled: true
        # The name of the material used.
        material: LEATHER_BOOTS
        # Is the jetpack craftable?
        craftable: true
# Infinity Laboratories Secret Items
# These secret items can only be created by learning the crafting
# recipe, which is kept secret by Infinity Laboratories.
    secretitem1:
        # Is this item enabled?
        enabled: true
        # The name of the material used.
        material: DIAMOND_BLOCK
        # Is this item craftable?
        craftable: true
    lavabucket:
        # Is this item enabled?
        enabled: true
        # The name of the material used.
        material: LAVA_BUCKET
        # Is this item craftable?
        craftable: true
    secretitem2:
        # Is this item enabled?
        enabled: true
        # The name of the material used.
        material: EMERALD
        # Is this item craftable?
        craftable: true
    secretitem3:
        # Is this item enabled?
        enabled: true
        # The name of the material used.
        material: NETHER_STAR
        # Is this item craftable?
        craftable: true
fuel:
    # Is fuel usage enabled?
    enabled: true
    # The name of the Material used.
    material: COAL
    # Durability of the Material (-1 for any), for example:
    # to match coal and charcoal, use -1. To match coal only, 0, and
    # charcoal, 1.
    durability: -1
