name: EasyJetpack
version: 2.0.0
description: Jetpacks and More!
authors: [jselby]
website: https://github.com/j-selby/EasyJetpack

main: net.jselby.ej.EasyJetpackPlugin

commands:
   ej:
      description: Various EasyJetpack admin commmands
      usage: /ej
      permission: easyjetpack.admin

permissions:
   easyjetpack.useAllJetpacks:
      description: Allows a player to use all jetpacks
      default: true
   easyjetpack.<jetpackname>:
      description: Allows a player to use a jetpack
   easyjetpack.admin:
      description: Allows access to /ej
      default: op
   easyjetpack.nofall:
      description: Disables all fall damage while wearing a jetpack
      default: op
